### ISSUE TITLE
Get Excalibur dependency from NPM

### ISSUE THREAD

**Issue by jedeen** [excaliburjs/generator-excalibur#3]
### Context
Currently, the generator pulls TypeScript from NPM and Excalibur from Bower. It would be simpler (and result in a less-cluttered directory) if Excalibur was also pulled from NPM.

### Proposal
Change the generator so it pulls Excalibur from NPM.

**Comment by jamonholmgren** [comment]
Yes please! Bower is having trouble on my system anyway:

```
$ npm --version
5.0.3
$ node --version
v8.1.2
$ bower
module.js:472
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:18:20
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

**Comment by jamonholmgren** [comment]
Nice!
